name: release

on:
  push:
    branches:
      - 'release/*'

jobs:
  continuous-deployment:
    env:
      VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
      VITE_NAVER_CLIENT_ID: ${{ secrets.VITE_NAVER_CLIENT_ID }}
      VITE_KAKAO_CLIENT_ID: ${{ secrets.VITE_KAKAO_CLIENT_ID }}
      VITE_NAVER_REDIRECT_URI: ${{ vars.VITE_NAVER_REDIRECT_URI }}
      VITE_KAKAO_REDIRECT_URI: ${{ vars.VITE_KAKAO_REDIRECT_URI }}
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23.6.1

      - name: Install dependencies
        uses: ./.github/actions/pnpm-install

      - name: Build
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
        run: pnpm build

      - name: Deploy to S3
        run: |
          aws s3 rm s3://${{ secrets.AWS_S3_BUCKET_NAME }} --recursive
          aws s3 cp --recursive --region ${{ secrets.AWS_REGION }} ./dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}

      - name: CloudFront Invalidate Cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths '/*'
